### ISSUE TITLE
list_accounts pagination is missing

### ISSUE THREAD

**Issue by leonid-comm-it** [aws-samples/aws-organizations-alternate-contact-manager#1]
Hello,
list_accounts_func() is missing pagination logics. This will cause some accounts in large organizations be skipped and leave them not updated. 

https://boto3.amazonaws.com/v1/documentation/api/latest/reference/services/organizations.html#Organizations.Client.list_accounts

Thank you.

**Comment by joaogabrielcarnevale** [comment]
Hi @leonid-comm-it,

Thanks for reporting the issue!

Issue fixed.

Regards, João Gabriel Carnevale.
